// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskSCSBOT(arg1:string):Promise<string>;

export function ClearMemory():Promise<void>;

export function ExportMemory():Promise<string>;

export function GetAIStatus():Promise<Record<string, any>>;

export function GetCurrentModel():Promise<string>;

export function GetModels():Promise<Array<string>>;

export function ImportMemory(arg1:string):Promise<void>;

export function LoginUser(arg1:string,arg2:string):Promise<string>;

export function RegisterUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetModel(arg1:string):Promise<void>;

export function SwitchModel():Promise<void>;
