// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskSCSBOT(arg1) {
  return window['go']['main']['App']['AskSCSBOT'](arg1);
}

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function ConnectDatabase() {
  return window['go']['main']['App']['ConnectDatabase']();
}

export function ExportMemory() {
  return window['go']['main']['App']['ExportMemory']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function RegisterUser(arg1, arg2) {
  return window['go']['main']['App']['RegisterUser'](arg1, arg2);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}
