// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AskSCSBOT(arg1:string):Promise<string>;

export function ClearMemory():Promise<void>;

export function ConnectDatabase():Promise<string>;

export function ExportMemory():Promise<string>;

export function GetModels():Promise<Array<string>>;

export function RegisterUser(arg1:services.RegistrationPayload,arg2:string):Promise<Record<string, any>>;

export function SetModel(arg1:string):Promise<void>;
